# Generated by Django 5.1.7 on 2025-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_cart_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
