# Generated by Django 5.1.6 on 2025-08-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
