# Generated by Django 5.1.6 on 2025-10-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('maquillage', 'Maquillage'), ('creme_beaute', 'Crème de Beauté'), ('vetement', 'Vêtement'), ('accessoire', 'Accessoire'), ('parfum', 'Parfum'), ('soin_cheveux', 'Soin Cheveux'), ('chaussure', 'Chaussure')], default='vetement', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
