# Generated by Django 5.1.6 on 2025-10-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_product_category_product_featured_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
