# Generated by Django 5.1.6 on 2025-10-18 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
